class CountryData {
  final String name;
  final String code;
  final String dialCode;
  final String flag;

  const CountryData({required this.name, required this.code, required this.dialCode, required this.flag});
}

const List<CountryData> allCountries = [
  CountryData(name: 'Afganistan', code: 'AF', dialCode: '+93', flag: '🇦🇫'),
  CountryData(name: 'Almanya', code: 'DE', dialCode: '+49', flag: '🇩🇪'),
  CountryData(name: 'Amerika Birleşik Devletleri', code: 'US', dialCode: '+1', flag: '🇺🇸'),
  CountryData(name: 'Andorra', code: 'AD', dialCode: '+376', flag: '🇦🇩'),
  CountryData(name: 'Angola', code: 'AO', dialCode: '+244', flag: '🇦🇴'),
  CountryData(name: 'Antigua ve Barbuda', code: 'AG', dialCode: '+1', flag: '🇦🇬'),
  CountryData(name: 'Arjantin', code: 'AR', dialCode: '+54', flag: '🇦🇷'),
  CountryData(name: 'Arnavutluk', code: 'AL', dialCode: '+355', flag: '🇦🇱'),
  CountryData(name: 'Avustralya', code: 'AU', dialCode: '+61', flag: '🇦🇺'),
  CountryData(name: 'Avusturya', code: 'AT', dialCode: '+43', flag: '🇦🇹'),
  CountryData(name: 'Azerbaycan', code: 'AZ', dialCode: '+994', flag: '🇦🇿'),
  CountryData(name: 'Bahamalar', code: 'BS', dialCode: '+1', flag: '🇧🇸'),
  CountryData(name: 'Bahreyn', code: 'BH', dialCode: '+973', flag: '🇧🇭'),
  CountryData(name: 'Bangladeş', code: 'BD', dialCode: '+880', flag: '🇧🇩'),
  CountryData(name: 'Barbados', code: 'BB', dialCode: '+1', flag: '🇧🇧'),
  CountryData(name: 'Batı Sahra', code: 'EH', dialCode: '+212', flag: '🇪🇭'),
  CountryData(name: 'Belçika', code: 'BE', dialCode: '+32', flag: '🇧🇪'),
  CountryData(name: 'Belize', code: 'BZ', dialCode: '+501', flag: '🇧🇿'),
  CountryData(name: 'Benin', code: 'BJ', dialCode: '+229', flag: '🇧🇯'),
  CountryData(name: 'Beyaz Rusya (Belarus)', code: 'BY', dialCode: '+375', flag: '🇧🇾'),
  CountryData(name: 'Bhutan', code: 'BT', dialCode: '+975', flag: '🇧🇹'),
  CountryData(name: 'Birleşik Arap Emirlikleri', code: 'AE', dialCode: '+971', flag: '🇦🇪'),
  CountryData(name: 'Birleşik Krallık', code: 'GB', dialCode: '+44', flag: '🇬🇧'),
  CountryData(name: 'Bolivya', code: 'BO', dialCode: '+591', flag: '🇧🇴'),
  CountryData(name: 'Bosna Hersek', code: 'BA', dialCode: '+387', flag: '🇧🇦'),
  CountryData(name: 'Botsvana', code: 'BW', dialCode: '+267', flag: '🇧🇼'),
  CountryData(name: 'Brezilya', code: 'BR', dialCode: '+55', flag: '🇧🇷'),
  CountryData(name: 'Brunei', code: 'BN', dialCode: '+673', flag: '🇧🇳'),
  CountryData(name: 'Bulgaristan', code: 'BG', dialCode: '+359', flag: '🇧🇬'),
  CountryData(name: 'Burkina Faso', code: 'BF', dialCode: '+226', flag: '🇧🇫'),
  CountryData(name: 'Burundi', code: 'BI', dialCode: '+257', flag: '🇧🇮'),
  CountryData(name: 'Cezayir', code: 'DZ', dialCode: '+213', flag: '🇩🇿'),
  CountryData(name: 'Cibuti', code: 'DJ', dialCode: '+253', flag: '🇩🇯'),
  CountryData(name: 'Çad', code: 'TD', dialCode: '+235', flag: '🇹🇩'),
  CountryData(name: 'Çekya', code: 'CZ', dialCode: '+420', flag: '🇨🇿'),
  CountryData(name: 'Çin', code: 'CN', dialCode: '+86', flag: '🇨🇳'),
  CountryData(name: 'Danimarka', code: 'DK', dialCode: '+45', flag: '🇩🇰'),
  CountryData(name: 'Doğu Timor', code: 'TL', dialCode: '+670', flag: '🇹🇱'),
  CountryData(name: 'Dominik Cumhuriyeti', code: 'DO', dialCode: '+1', flag: '🇩🇴'),
  CountryData(name: 'Dominika', code: 'DM', dialCode: '+1', flag: '🇩🇲'),
  CountryData(name: 'Ekvador', code: 'EC', dialCode: '+593', flag: '🇪🇨'),
  CountryData(name: 'Ekvator Ginesi', code: 'GQ', dialCode: '+240', flag: '🇬🇶'),
  CountryData(name: 'El Salvador', code: 'SV', dialCode: '+503', flag: '🇸🇻'),
  CountryData(name: 'Endonezya', code: 'ID', dialCode: '+62', flag: '🇮🇩'),
  CountryData(name: 'Eritre', code: 'ER', dialCode: '+291', flag: '🇪🇷'),
  CountryData(name: 'Ermenistan', code: 'AM', dialCode: '+374', flag: '🇦🇲'),
  CountryData(name: 'Estonya', code: 'EE', dialCode: '+372', flag: '🇪🇪'),
  CountryData(name: 'Etiyopya', code: 'ET', dialCode: '+251', flag: '🇪🇹'),
  CountryData(name: 'Fas', code: 'MA', dialCode: '+212', flag: '🇲🇦'),
  CountryData(name: 'Fiji', code: 'FJ', dialCode: '+679', flag: '🇫🇯'),
  CountryData(name: 'Fildişi Sahili', code: 'CI', dialCode: '+225', flag: '🇨🇮'),
  CountryData(name: 'Filipinler', code: 'PH', dialCode: '+63', flag: '🇵🇭'),
  CountryData(name: 'Filistin', code: 'PS', dialCode: '+970', flag: '🇵🇸'),
  CountryData(name: 'Finlandiya', code: 'FI', dialCode: '+358', flag: '🇫🇮'),
  CountryData(name: 'Fransa', code: 'FR', dialCode: '+33', flag: '🇫🇷'),
  CountryData(name: 'Gabon', code: 'GA', dialCode: '+241', flag: '🇬🇦'),
  CountryData(name: 'Gambiya', code: 'GM', dialCode: '+220', flag: '🇬🇲'),
  CountryData(name: 'Gana', code: 'GH', dialCode: '+233', flag: '🇬🇭'),
  CountryData(name: 'Gine', code: 'GN', dialCode: '+224', flag: '🇬🇳'),
  CountryData(name: 'Gine Bissau', code: 'GW', dialCode: '+245', flag: '🇬🇼'),
  CountryData(name: 'Grenada', code: 'GD', dialCode: '+1', flag: '🇬🇩'),
  CountryData(name: 'Guatemala', code: 'GT', dialCode: '+502', flag: '🇬🇹'),
  CountryData(name: 'Guyana', code: 'GY', dialCode: '+592', flag: '🇬🇾'),
  CountryData(name: 'Güney Afrika', code: 'ZA', dialCode: '+27', flag: '🇿🇦'),
  CountryData(name: 'Güney Kore', code: 'KR', dialCode: '+82', flag: '🇰🇷'),
  CountryData(name: 'Güney Sudan', code: 'SS', dialCode: '+211', flag: '🇸🇸'),
  CountryData(name: 'Gürcistan', code: 'GE', dialCode: '+995', flag: '🇬🇪'),
  CountryData(name: 'Haiti', code: 'HT', dialCode: '+509', flag: '🇭🇹'),
  CountryData(name: 'Hırvatistan', code: 'HR', dialCode: '+385', flag: '🇭🇷'),
  CountryData(name: 'Hindistan', code: 'IN', dialCode: '+91', flag: '🇮🇳'),
  CountryData(name: 'Hollanda', code: 'NL', dialCode: '+31', flag: '🇳🇱'),
  CountryData(name: 'Honduras', code: 'HN', dialCode: '+504', flag: '🇭🇳'),
  CountryData(name: 'Hong Kong', code: 'HK', dialCode: '+852', flag: '🇭🇰'),
  CountryData(name: 'Irak', code: 'IQ', dialCode: '+964', flag: '🇮🇶'),
  CountryData(name: 'İran', code: 'IR', dialCode: '+98', flag: '🇮🇷'),
  CountryData(name: 'İrlanda', code: 'IE', dialCode: '+353', flag: '🇮🇪'),
  CountryData(name: 'İspanya', code: 'ES', dialCode: '+34', flag: '🇪🇸'),
  CountryData(name: 'İsrail', code: 'IL', dialCode: '+972', flag: '🇮🇱'),
  CountryData(name: 'İsveç', code: 'SE', dialCode: '+46', flag: '🇸🇪'),
  CountryData(name: 'İsviçre', code: 'CH', dialCode: '+41', flag: '🇨🇭'),
  CountryData(name: 'İtalya', code: 'IT', dialCode: '+39', flag: '🇮🇹'),
  CountryData(name: 'İzlanda', code: 'IS', dialCode: '+354', flag: '🇮🇸'),
  CountryData(name: 'Jamaika', code: 'JM', dialCode: '+1', flag: '🇯🇲'),
  CountryData(name: 'Japonya', code: 'JP', dialCode: '+81', flag: '🇯🇵'),
  CountryData(name: 'Kamboçya', code: 'KH', dialCode: '+855', flag: '🇰🇭'),
  CountryData(name: 'Kamerun', code: 'CM', dialCode: '+237', flag: '🇨🇲'),
  CountryData(name: 'Kanada', code: 'CA', dialCode: '+1', flag: '🇨🇦'),
  CountryData(name: 'Karadağ', code: 'ME', dialCode: '+382', flag: '🇲🇪'),
  CountryData(name: 'Katar', code: 'QA', dialCode: '+974', flag: '🇶🇦'),
  CountryData(name: 'Kazakistan', code: 'KZ', dialCode: '+7', flag: '🇰🇿'),
  CountryData(name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪'),
  CountryData(name: 'Kıbrıs', code: 'CY', dialCode: '+357', flag: '🇨🇾'),
  CountryData(name: 'Kırgızistan', code: 'KG', dialCode: '+996', flag: '🇰🇬'),
  CountryData(name: 'Kiribati', code: 'KI', dialCode: '+686', flag: '🇰🇮'),
  CountryData(name: 'Kolombiya', code: 'CO', dialCode: '+57', flag: '🇨🇴'),
  CountryData(name: 'Komorlar', code: 'KM', dialCode: '+269', flag: '🇰🇲'),
  CountryData(name: 'Kongo Cumhuriyeti', code: 'CG', dialCode: '+242', flag: '🇨🇬'),
  CountryData(name: 'Kongo DC', code: 'CD', dialCode: '+243', flag: '🇨🇩'),
  CountryData(name: 'Kosta Rika', code: 'CR', dialCode: '+506', flag: '🇨🇷'),
  CountryData(name: 'Kuveyt', code: 'KW', dialCode: '+965', flag: '🇰🇼'),
  CountryData(name: 'Kuzey Kore', code: 'KP', dialCode: '+850', flag: '🇰🇵'),
  CountryData(name: 'Kuzey Makedonya', code: 'MK', dialCode: '+389', flag: '🇲🇰'),
  CountryData(name: 'Küba', code: 'CU', dialCode: '+53', flag: '🇨🇺'),
  CountryData(name: 'Laos', code: 'LA', dialCode: '+856', flag: '🇱🇦'),
  CountryData(name: 'Lesotho', code: 'LS', dialCode: '+266', flag: '🇱🇸'),
  CountryData(name: 'Letonya', code: 'LV', dialCode: '+371', flag: '🇱🇻'),
  CountryData(name: 'Liberya', code: 'LR', dialCode: '+231', flag: '🇱🇷'),
  CountryData(name: 'Libya', code: 'LY', dialCode: '+218', flag: '🇱🇾'),
  CountryData(name: 'Lihtenştayn', code: 'LI', dialCode: '+423', flag: '🇱🇮'),
  CountryData(name: 'Litvanya', code: 'LT', dialCode: '+370', flag: '🇱🇹'),
  CountryData(name: 'Lübnan', code: 'LB', dialCode: '+961', flag: '🇱🇧'),
  CountryData(name: 'Lüksemburg', code: 'LU', dialCode: '+352', flag: '🇱🇺'),
  CountryData(name: 'Macaristan', code: 'HU', dialCode: '+36', flag: '🇭🇺'),
  CountryData(name: 'Madagaskar', code: 'MG', dialCode: '+261', flag: '🇲🇬'),
  CountryData(name: 'Makao', code: 'MO', dialCode: '+853', flag: '🇲🇴'),
  CountryData(name: 'Malavi', code: 'MW', dialCode: '+265', flag: '🇲🇼'),
  CountryData(name: 'Maldivler', code: 'MV', dialCode: '+960', flag: '🇲🇻'),
  CountryData(name: 'Malezya', code: 'MY', dialCode: '+60', flag: '🇲🇾'),
  CountryData(name: 'Mali', code: 'ML', dialCode: '+223', flag: '🇲🇱'),
  CountryData(name: 'Malta', code: 'MT', dialCode: '+356', flag: '🇲🇹'),
  CountryData(name: 'Marshall Adaları', code: 'MH', dialCode: '+692', flag: '🇲🇭'),
  CountryData(name: 'Mauritius', code: 'MU', dialCode: '+230', flag: '🇲🇺'),
  CountryData(name: 'Mısır', code: 'EG', dialCode: '+20', flag: '🇪🇬'),
  CountryData(name: 'Mikronezya', code: 'FM', dialCode: '+691', flag: '🇫🇲'),
  CountryData(name: 'Moğolistan', code: 'MN', dialCode: '+976', flag: '🇲🇳'),
  CountryData(name: 'Moldova', code: 'MD', dialCode: '+373', flag: '🇲🇩'),
  CountryData(name: 'Monako', code: 'MC', dialCode: '+377', flag: '🇲🇨'),
  CountryData(name: 'Moritanya', code: 'MR', dialCode: '+222', flag: '🇲🇷'),
  CountryData(name: 'Mozambik', code: 'MZ', dialCode: '+258', flag: '🇲🇿'),
  CountryData(name: 'Myanmar (Burma)', code: 'MM', dialCode: '+95', flag: '🇲🇲'),
  CountryData(name: 'Namibya', code: 'NA', dialCode: '+264', flag: '🇳🇦'),
  CountryData(name: 'Nauru', code: 'NR', dialCode: '+674', flag: '🇳🇷'),
  CountryData(name: 'Nepal', code: 'NP', dialCode: '+977', flag: '🇳🇵'),
  CountryData(name: 'Nijer', code: 'NE', dialCode: '+227', flag: '🇳🇪'),
  CountryData(name: 'Nijerya', code: 'NG', dialCode: '+234', flag: '🇳🇬'),
  CountryData(name: 'Nikaragua', code: 'NI', dialCode: '+505', flag: '🇳🇮'),
  CountryData(name: 'Norveç', code: 'NO', dialCode: '+47', flag: '🇳🇴'),
  CountryData(name: 'Orta Afrika Cumhuriyeti', code: 'CF', dialCode: '+236', flag: '🇨🇫'),
  CountryData(name: 'Özbekistan', code: 'UZ', dialCode: '+998', flag: '🇺🇿'),
  CountryData(name: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰'),
  CountryData(name: 'Palau', code: 'PW', dialCode: '+680', flag: '🇵🇼'),
  CountryData(name: 'Panama', code: 'PA', dialCode: '+507', flag: '🇵🇦'),
  CountryData(name: 'Papua Yeni Gine', code: 'PG', dialCode: '+675', flag: '🇵🇬'),
  CountryData(name: 'Paraguay', code: 'PY', dialCode: '+595', flag: '🇵🇾'),
  CountryData(name: 'Peru', code: 'PE', dialCode: '+51', flag: '🇵🇪'),
  CountryData(name: 'Polonya', code: 'PL', dialCode: '+48', flag: '🇵🇱'),
  CountryData(name: 'Portekiz', code: 'PT', dialCode: '+351', flag: '🇵🇹'),
  CountryData(name: 'Porto Riko', code: 'PR', dialCode: '+1', flag: '🇵🇷'),
  CountryData(name: 'Romanya', code: 'RO', dialCode: '+40', flag: '🇷🇴'),
  CountryData(name: 'Ruanda', code: 'RW', dialCode: '+250', flag: '🇷🇼'),
  CountryData(name: 'Rusya', code: 'RU', dialCode: '+7', flag: '🇷🇺'),
  CountryData(name: 'Saint Kitts ve Nevis', code: 'KN', dialCode: '+1', flag: '🇰🇳'),
  CountryData(name: 'Saint Lucia', code: 'LC', dialCode: '+1', flag: '🇱🇨'),
  CountryData(name: 'Saint Vincent ve Grenadinler', code: 'VC', dialCode: '+1', flag: '🇻🇨'),
  CountryData(name: 'Samoa', code: 'WS', dialCode: '+685', flag: '🇼🇸'),
  CountryData(name: 'San Marino', code: 'SM', dialCode: '+378', flag: '🇸🇲'),
  CountryData(name: 'Sao Tome ve Principe', code: 'ST', dialCode: '+239', flag: '🇸🇹'),
  CountryData(name: 'Senegal', code: 'SN', dialCode: '+221', flag: '🇸🇳'),
  CountryData(name: 'Seyşeller', code: 'SC', dialCode: '+248', flag: '🇸🇨'),
  CountryData(name: 'Sırbistan', code: 'RS', dialCode: '+381', flag: '🇷🇸'),
  CountryData(name: 'Sierra Leone', code: 'SL', dialCode: '+232', flag: '🇸🇱'),
  CountryData(name: 'Singapur', code: 'SG', dialCode: '+65', flag: '🇸🇬'),
  CountryData(name: 'Slovakya', code: 'SK', dialCode: '+421', flag: '🇸🇰'),
  CountryData(name: 'Slovenya', code: 'SI', dialCode: '+386', flag: '🇸🇮'),
  CountryData(name: 'Solomon Adaları', code: 'SB', dialCode: '+677', flag: '🇸🇧'),
  CountryData(name: 'Somali', code: 'SO', dialCode: '+252', flag: '🇸🇴'),
  CountryData(name: 'Sri Lanka', code: 'LK', dialCode: '+94', flag: '🇱🇰'),
  CountryData(name: 'Sudan', code: 'SD', dialCode: '+249', flag: '🇸🇩'),
  CountryData(name: 'Surinam', code: 'SR', dialCode: '+597', flag: '🇸🇷'),
  CountryData(name: 'Suriye', code: 'SY', dialCode: '+963', flag: '🇸🇾'),
  CountryData(name: 'Suudi Arabistan', code: 'SA', dialCode: '+966', flag: '🇸🇦'),
  CountryData(name: 'Svaziland', code: 'SZ', dialCode: '+268', flag: '🇸🇿'),
  CountryData(name: 'Şili', code: 'CL', dialCode: '+56', flag: '🇨🇱'),
  CountryData(name: 'Tacikistan', code: 'TJ', dialCode: '+992', flag: '🇹🇯'),
  CountryData(name: 'Tanzanya', code: 'TZ', dialCode: '+255', flag: '🇹🇿'),
  CountryData(name: 'Tayland', code: 'TH', dialCode: '+66', flag: '🇹🇭'),
  CountryData(name: 'Tayvan', code: 'TW', dialCode: '+886', flag: '🇹🇼'),
  CountryData(name: 'Togo', code: 'TG', dialCode: '+228', flag: '🇹🇬'),
  CountryData(name: 'Tonga', code: 'TO', dialCode: '+676', flag: '🇹🇴'),
  CountryData(name: 'Trinidad ve Tobago', code: 'TT', dialCode: '+1', flag: '🇹🇹'),
  CountryData(name: 'Tunus', code: 'TN', dialCode: '+216', flag: '🇹🇳'),
  CountryData(name: 'Tuvalu', code: 'TV', dialCode: '+688', flag: '🇹🇻'),
  CountryData(name: 'Türkiye', code: 'TR', dialCode: '+90', flag: '🇹🇷'),
  CountryData(name: 'Türkmenistan', code: 'TM', dialCode: '+993', flag: '🇹🇲'),
  CountryData(name: 'Uganda', code: 'UG', dialCode: '+256', flag: '🇺🇬'),
  CountryData(name: 'Ukrayna', code: 'UA', dialCode: '+380', flag: '🇺🇦'),
  CountryData(name: 'Umman', code: 'OM', dialCode: '+968', flag: '🇴🇲'),
  CountryData(name: 'Uruguay', code: 'UY', dialCode: '+598', flag: '🇺🇾'),
  CountryData(name: 'Ürdün', code: 'JO', dialCode: '+962', flag: '🇯🇴'),
  CountryData(name: 'Vanuatu', code: 'VU', dialCode: '+678', flag: '🇻🇺'),
  CountryData(name: 'Vatikan', code: 'VA', dialCode: '+379', flag: '🇻🇦'),
  CountryData(name: 'Venezuela', code: 'VE', dialCode: '+58', flag: '🇻🇪'),
  CountryData(name: 'Vietnam', code: 'VN', dialCode: '+84', flag: '🇻🇳'),
  CountryData(name: 'Yemen', code: 'YE', dialCode: '+967', flag: '🇾🇪'),
  CountryData(name: 'Yeni Zelanda', code: 'NZ', dialCode: '+64', flag: '🇳🇿'),
  CountryData(name: 'Yeşil Burun Adaları', code: 'CV', dialCode: '+238', flag: '🇨🇻'),
  CountryData(name: 'Zambiya', code: 'ZM', dialCode: '+260', flag: '🇿🇲'),
  CountryData(name: 'Zimbabve', code: 'ZW', dialCode: '+263', flag: '🇿🇼'),
];
